# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: contextual_model.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='contextual_model.proto',
  package='rus.model',
  syntax='proto2',
  serialized_pb=_b('\n\x16\x63ontextual_model.proto\x12\trus.model\"p\n\x0f\x43ontextualModel\x12\t\n\x01R\x18\x01 \x02(\x02\x12\r\n\x05\x64\x65lta\x18\x02 \x02(\x02\x12\x0f\n\x07\x65psilon\x18\x03 \x02(\x02\x12\x0c\n\x04\x64ims\x18\x04 \x02(\x05\x12\x0e\n\x06mu_hat\x18\x05 \x03(\x02\x12\t\n\x01\x66\x18\x06 \x03(\x02\x12\t\n\x01\x42\x18\x07 \x03(\x02\x42\x03\x80\x01\x01')
)




_CONTEXTUALMODEL = _descriptor.Descriptor(
  name='ContextualModel',
  full_name='rus.model.ContextualModel',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='R', full_name='rus.model.ContextualModel.R', index=0,
      number=1, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='delta', full_name='rus.model.ContextualModel.delta', index=1,
      number=2, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='epsilon', full_name='rus.model.ContextualModel.epsilon', index=2,
      number=3, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dims', full_name='rus.model.ContextualModel.dims', index=3,
      number=4, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mu_hat', full_name='rus.model.ContextualModel.mu_hat', index=4,
      number=5, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='f', full_name='rus.model.ContextualModel.f', index=5,
      number=6, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='B', full_name='rus.model.ContextualModel.B', index=6,
      number=7, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=37,
  serialized_end=149,
)

DESCRIPTOR.message_types_by_name['ContextualModel'] = _CONTEXTUALMODEL
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ContextualModel = _reflection.GeneratedProtocolMessageType('ContextualModel', (_message.Message,), dict(
  DESCRIPTOR = _CONTEXTUALMODEL,
  __module__ = 'contextual_model_pb2'
  # @@protoc_insertion_point(class_scope:rus.model.ContextualModel)
  ))
_sym_db.RegisterMessage(ContextualModel)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\200\001\001'))
# @@protoc_insertion_point(module_scope)
